### ISSUE TITLE
适配 Halo 2.0

### ISSUE THREAD

**Issue by ruibaby** [daifiyum/halo-theme-MaterialYour#12]
目前 Halo 2.0 已经发布到 2.0-rc.1，主题的 API 已经基本稳定，可以考虑将这个主题适配到 2.0。

2.0 的主题开发文档可参考：https://docs.halo.run/2.0.0-SNAPSHOT/category/%E4%B8%BB%E9%A2%98%E5%BC%80%E5%8F%91

有开发上的任何问题和建议可以向 Halo 提交 issue。

**Comment by daifiyum** [comment]
在了，在了😎
https://github.com/daifiyum/halo-theme-MaterialYour/tree/next

**Comment by lcese** [comment]
目前主题 已经更新到2.9了。
