### ISSUE TITLE
非常赞的一个博客模板

### ISSUE THREAD

**Issue by demosu** [daifiyum/halo-theme-MaterialYour#2]
主题仓库里的众多模板都没看上，最后迷上了这款简洁风的。非常棒

**Comment by demosu** [comment]
我看相册页面无法使用，友情链接页面也不一样。是后期还有更新吗？期待

**Comment by daifiyum** [comment]
> 我看相册页面无法使用，友情链接页面也不一样。是后期还有更新吗？期待


推荐安装仓库里的，和我博客一样，发布版比较拉跨
相册可以使用，不过没有好好写这个页面，比较简陋，你有使用问题，可以博客留言
友情链接页面如果使用官方默认的，就无法在这个页面里加评论，所以我新建一个友情页面，添加链接的方式不变（后台友链页面，有不可用提示，不用管他）

不会停更的，有重度需求或不满意的地方会加速更新的
