### ISSUE TITLE
api key null

### ISSUE THREAD

**Issue by qianyu223** [daifiyum/halo-theme-MaterialYour#3]
在最新开发版本下未开启API ACCESS 但是首页刷新会提示api key null  
疑似因为引入mp.js 导致/api/content/themes/activation/settings   403 API has been disabled by blogger currently

**Comment by daifiyum** [comment]
> 在最新开发版本下未开启API ACCESS 但是首页刷新会提示api key null 疑似因为引入mp.js 导致/api/content/themes/activation/settings 403 API has been disabled by blogger currently

已修复，感谢提出Issues
