### ISSUE TITLE
增加默认镇站图

### ISSUE THREAD

**Issue by awxiaoxian2020** [daifiyum/halo-theme-MaterialYour#7]
这样在首次启用时也能有比较好的浏览体验

**Comment by daifiyum** [comment]
这样不错，马上加个，我没怎么考虑初次安装的样子😂

**Comment by daifiyum** [comment]
> 这样在首次启用时也能有比较好的浏览体验

已加，还有其他的设置项都加了默认设置
![屏幕截图 2022-06-29 185254.png](https://img.dnxrzl.com/2022/06/29/d80a01f02fd9f.png)

**Comment by awxiaoxian2020** [comment]
> > 这样在首次启用时也能有比较好的浏览体验
> 
> 已加，还有其他的设置项都加了默认设置 ![屏幕截图 2022-06-29 185254.png](https://camo.githubusercontent.com/8a5611e653831a81124beec3461cfb2b436374765e2d9f573d229b8ec6264843/68747470733a2f2f696d672e646e78727a6c2e636f6d2f323032322f30362f32392f643830613031663032666439662e706e67)

灰常感谢！
