### ISSUE TITLE
halo公共底部模板是不是没放对位置

### ISSUE THREAD

**Issue by howe0116** [daifiyum/halo-theme-MaterialYour#9]
halo设置的页脚信息和统计代码没和主题页脚在一起,
建议把macro.ftl的<@global.footer />移到footer.ftl里

很棒的主题~另外想问一下可以自定义字体吗?

**Comment by daifiyum** [comment]
> halo设置的页脚信息和统计代码没和主题页脚在一起, 建议把macro.ftl的<@global.footer />移到footer.ftl里
> 
> 很棒的主题~另外想问一下可以自定义字体吗?

谢谢建议，字体的自定义目前没有做，不过你也可以自己实现看看，不懂得地方，我可以给你看看

**Comment by howe0116** [comment]
> > halo设置的页脚信息和统计代码没和主题页脚在一起, 建议把macro.ftl的<@global.footer />移到footer.ftl里
> > 很棒的主题~另外想问一下可以自定义字体吗?
> 
> 谢谢建议，字体的自定义目前没有做，不过你也可以自己实现看看，不懂得地方，我可以给你看看

好的，主要还是找不到在哪修改。

**Comment by howe0116** [comment]
> > > halo设置的页脚信息和统计代码没和主题页脚在一起, 建议把macro.ftl的<@global.footer />移到footer.ftl里
> > > 很棒的主题~另外想问一下可以自定义字体吗?
> > 
> > 
> > 谢谢建议，字体的自定义目前没有做，不过你也可以自己实现看看，不懂得地方，我可以给你看看
> > 好的，主要还是找不到在哪修改。



> > > halo设置的页脚信息和统计代码没和主题页脚在一起, 建议把macro.ftl的<@global.footer />移到footer.ftl里
> > > 很棒的主题~另外想问一下可以自定义字体吗?
> > 
> > 
> > 谢谢建议，字体的自定义目前没有做，不过你也可以自己实现看看，不懂得地方，我可以给你看看
好的，主要还是找不到在哪修改。

**Comment by daifiyum** [comment]
有字体文件吗，我来改改

**Comment by daifiyum** [comment]
![微信图片_20220630212901.png](https://img.dnxrzl.com/2022/06/30/dc124c67c071a.png)
在source\fonts\文件夹下新建一个文件夹并放入你的字体文件，然后去source\css\selfFonts.css样式文件里添加自定义字体的css样式，可以给body标签添加，这样页面所有字体都会被改变

**Comment by howe0116** [comment]
> 有字体文件吗，我来改改

刚刚试了一下[字体](https://howe0116.com/upload/2022/06/LXGWWenKaiMono-Regular.ttf) 没成~orz

**Comment by daifiyum** [comment]
> > 有字体文件吗，我来改改
> 
> 刚刚试了一下[字体](https://howe0116.com/upload/2022/06/LXGWWenKaiMono-Regular.ttf) 没成~orz

可以这样自定义，你看看
![微信图片_20220701080742.png](https://img.dnxrzl.com/2022/07/01/a4337e2c0bea8.png)
![微信图片_20220701080728.png](https://img.dnxrzl.com/2022/07/01/6c672ba939b45.png)

**Comment by howe0116** [comment]
好的好的~ 感谢~
